# assuming flang is default fortan compiler for windows,
# by default, version 5 is installed. Update to 19:
#fortran_compiler_version:  # [win]
#  - 19                     # [win]

c_compiler_version:  # [win]
  - 21               # [win]

c_linker_version:  # [win]
  - 21             # [win]

# # use newer numpy; can be removed once migrated for numpy 2.0
# numpy:
#   - 1.26
#   - 1.26
#   - 1.26
#   - 1.26
